# Generated by Django 4.2.4 on 2023-10-25 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateField(default=datetime.datetime(2023, 10, 25, 10, 18, 36, 502339, tzinfo=datetime.timezone.utc))),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('price', models.IntegerField()),
                ('due_date', models.DateField(default=datetime.datetime(2023, 10, 25, 10, 18, 36, 502339, tzinfo=datetime.timezone.utc))),
                ('image', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Deleted')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(1, 'Зарегистрирован'), (2, 'Проверяется'), (3, 'Принято'), (4, 'Отказано'), (5, 'Удалено')], max_length=255, null=True)),
                ('creation_date', models.DateField(default=datetime.datetime(2023, 10, 25, 10, 18, 36, 502339, tzinfo=datetime.timezone.utc))),
                ('approving_date', models.DateField(default=datetime.datetime(2023, 10, 25, 10, 18, 36, 502339, tzinfo=datetime.timezone.utc))),
                ('publication_date', models.DateField(default=datetime.datetime(2023, 10, 25, 10, 18, 36, 502339, tzinfo=datetime.timezone.utc))),
                ('services', models.ManyToManyField(null=True, to='myapp.service', verbose_name='Сервисы')),
            ],
        ),
    ]
