# Generated by Django 4.2.4 on 2023-10-25 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approving_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 25, 21, 33, 14, 565883, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='application',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 25, 21, 33, 14, 565866, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='application',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 25, 21, 33, 14, 565894, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 25, 21, 33, 14, 564979, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 10, 25, 21, 33, 14, 564928, tzinfo=datetime.timezone.utc)),
        ),
    ]
